apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kubevirt-ch-vm
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 1024Mi
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootfs 
          - cdrom:
              bus: sata
            name: cloudinit
      volumes:
      - dataVolume:
          name: ch-test-dv
        name: rootfs
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            users
            - name: cloud
              plain_text_passwd: cloud123
              lock_passwd: False
        name: cloudinit
  dataVolumeTemplates:      
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: ch-test-dv
    spec:
      ... 
