apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: kubevirt-ch-vm
  name: kubevirt-ch-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: kubevirt-ch-vm
    spec:
      domain:
        firmware:
          kernelBoot:
            container:
              image: harshitg/hypervisor-fw:mariner
              kernelPath: /boot/hypervisor-fw
              imagePullPolicy: Always
        devices:
          autoattachGraphicsDevice: false
          autoattachMemBalloon: false
          disks:
          - disk:
              bus: virtio
            name: rootfs 
          - disk:
              bus: virtio
            name: cloudinit
        cpu:
          cores: 2
        resources:
          requests:
            memory: 1024Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: ch-test-dv
        name: rootfs
      - dataVolume:
          name: ch-cloudinit-dv
        name: cloudinit
