apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.25.4
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
cpuManagerPolicy: static
kind: KubeletConfiguration
kubeReserved:
  cpu: '1'
  memory: 1500Mi
systemReserved:
  cpu: '1'
  memory: 500Mi
