load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "kvm-caps-info-plugin_amd64.go",
        "kvm-caps-info-plugin_arm64.go",
        "kvm-caps-info-plugin_s390x.go",
        "node-labeller.go",
        "types.go",
        "virtualization-capabilities-libvirt-qemu.go",
    ],
    cgo = True,
    importpath = "kubevirt.io/kubevirt/cmd/virt-launcher/node-labeller",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/virt-launcher/virt-capabilities:go_default_library",
        "//staging/src/kubevirt.io/api/core/v1:go_default_library",
        "//vendor/libvirt.org/go/libvirtxml:go_default_library",
    ] + select({
        "@io_bazel_rules_go//go/platform:amd64": [
            "//staging/src/kubevirt.io/client-go/log:go_default_library",
        ],
        "//conditions:default": [],
    }),
)

go_binary(
    name = "node-labeller",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
